### ISSUE TITLE
404 from MLCSU site promoting conference

### ISSUE THREAD

**Issue by AndyMcCannNHS** [nhs-r-community/conference-2024#1]
webpage 
https://www.midlandsandlancashirecsu.nhs.uk/registration-open-for-nhs-r-community-annual-conference/
links to
https://nhsrcommunity.com/events/#event_type-conferences
but that gives a 404 error

**Comment by Lextuga007** [comment]
Thanks for raising this! I'd shared the events link some time ago, before the Quarto site was set up. The links are now https://nhsrcommunity.com/conference24.html to go directly to the conference page or https://nhsrcommunity.com/events.html which is all our events.

**Comment by Lextuga007** [comment]
I've raised this as an issue on the website https://github.com/nhs-r-community/nhs-r-community/issues/258 to track and fix there as it might be useful to have a redirection set up. It also highlighted the current conference page is time specific with 24 in the title.
