### ISSUE TITLE
Slides for: A method to apply temporal graph analysis on electronic patient record data to explore healthcare professional patient interaction intensity.

### ISSUE THREAD

**Issue by jbooth04BBK** [nhs-r-community/conference-2024#27]
# Declarations

- [ x] I've read the repository README.
- [x ] I've seen the LICENSE used in this repository and understand that this will apply to my slides.
- [ x] I'll add my slides* to the `Talks` folder and name them in the form `2024-11-DD_surnames_presentation-title`, where `DD` is the date the presentation was given (`21` or `22`).

*If you would rather add a link to your slides, please create a simple markdown and add that to the `Talks` folder instead. Example: https://github.com/nhs-r-community/conference-2024/blob/main/Talks/2024-11-22_davies_reusable.md

**Comment by jbooth04BBK** [comment]
[2024-11-22_booth_temporal_graph_analysis.pptx](https://github.com/user-attachments/files/18108870/2024-11-22_booth_temporal_graph_analysis.pptx)

**Comment by anyaferguson** [comment]
Thanks @jbooth04BBK. I've added the slides to the Talks folder in pull request #31.
